#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

set -e
# Run formatter to format code before commit
before=$(git diff --name-only | wc -l)
./gradlew googleJavaFormat
after=$(git diff --name-only | wc -l)
if [ "$before" != "$after" ]; then
    echo "Commit aborted because unformatted files found. Please format and commit again"
	exit 1
fi